project:
  type: book
  output-dir: docs
book:
  title: "Basic R Course"
  author: "Sara Baart, David Nieuwenhuijse, Sten Willemsen, Sanne Hoeks, Elrozy Andrinopoulou, Elizabeth Ribble, Karl Brand"
  date: "08-11-2023"
  chapters:
    - index.qmd
    - introduction_history.qmd
    - part: Importing_Saving.qmd
      chapters: 
        - Importing_Saving_practical.qmd
    - part: Common_Objects.qmd
      chapters: 
        - Common_Objects_practical.qmd
    - part: Indexing_Subsetting.qmd
      chapters: 
        - Indexing_Subsetting_practical.qmd
    - part: objects.qmd
      chapters:
        - objects_practical.qmd
        - objects_practical_answers.qmd
    - part: manipulating_data.qmd
      chapters:
        - manipulating_data_practical.qmd
        - manipulating_data_practical_answers.qmd
    - part: Datacleaning.qmd
      chapters:
        - Datacleaning_practical.qmd
        - Datacleaning_answers.qmd
    - part: Analysis.qmd
      chapters:
        - Analysis_practical.qmd
        - Analysis_answers.qmd
    - part: basic_plotting_intro.qmd
      chapters:
        - basic_plotting.qmd
    - part: basic_plotting_practicals_intro.qmd
      chapters: 
        - basic_plotting_practicals_questions.qmd
        - basic_plotting_practicals_answers.qmd
    - part: ggplot2_intro.qmd
      chapters:
        - ggplot2.qmd
    - part: ggplot2_practicals_intro.qmd
      chapters:
        - ggplot2_practicals_questions.qmd
        - ggplot2_practicals_answers.qmd
    - part: functions_intro.qmd
      chapters:
        - functions_types.qmd
        - functions_arguments.qmd
        - functions_custom.qmd
        - functions_conditional.qmd
    - part: functions_practicals1_intro.qmd
      chapters:
        - functions_practicals1_questions.qmd
        - functions_practicals1_answers.qmd
    - part: functions_intro2.qmd
      chapters:
        - functions_scoping.qmd
        - functions_decoration.qmd
        - functions_looping.qmd
        - functions_apply.qmd
    - part: functions_practicals2_intro.qmd
      chapters:
        - functions_practicals2_questions.qmd
        - functions_practicals2_answers.qmd
    - basic_markdown.qmd
    - basic_markdown_practicals_questions.qmd
    - codeblocks.qmd
    - tidyverse.qmd
  repo-url: https://github.com/dnieuw/BasicRcourseEMC
  repo-actions: [edit]
  downloads: [pdf]

format:
  html:
    theme:
      light: cosmo
      dark: solar
  pdf:
    documentclass: scrreprt

editor: visual

number-depth: 2